// Code generated by entc, DO NOT EDIT.

package tskvdictionary

const (
	// Label holds the string label denoting the tskvdictionary type in the database.
	Label = "ts_kv_dictionary"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// Table holds the table name of the tskvdictionary in the database.
	Table = "ts_kv_dictionary"
)

// Columns holds all SQL columns for tskvdictionary fields.
var Columns = []string{
	FieldID,
	FieldKey,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
)
