// Code generated by entc, DO NOT EDIT.

package tskvlatest

import (
	"tsdb-ent-example/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntityID), v))
	})
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKey), v))
	})
}

// BoolV applies equality check predicate on the "bool_v" field. It's identical to BoolVEQ.
func BoolV(v bool) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBoolV), v))
	})
}

// StrV applies equality check predicate on the "str_v" field. It's identical to StrVEQ.
func StrV(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStrV), v))
	})
}

// LongV applies equality check predicate on the "long_v" field. It's identical to LongVEQ.
func LongV(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLongV), v))
	})
}

// DblV applies equality check predicate on the "dbl_v" field. It's identical to DblVEQ.
func DblV(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDblV), v))
	})
}

// JSONV applies equality check predicate on the "json_v" field. It's identical to JSONVEQ.
func JSONV(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJSONV), v))
	})
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTs), v))
	})
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntityID), v))
	})
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEntityID), v))
	})
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEntityID), v...))
	})
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEntityID), v...))
	})
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEntityID), v))
	})
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEntityID), v))
	})
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEntityID), v))
	})
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v uuid.UUID) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEntityID), v))
	})
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldKey), v))
	})
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldKey), v))
	})
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...int) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldKey), v...))
	})
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...int) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldKey), v...))
	})
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldKey), v))
	})
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldKey), v))
	})
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldKey), v))
	})
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v int) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldKey), v))
	})
}

// BoolVEQ applies the EQ predicate on the "bool_v" field.
func BoolVEQ(v bool) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBoolV), v))
	})
}

// BoolVNEQ applies the NEQ predicate on the "bool_v" field.
func BoolVNEQ(v bool) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBoolV), v))
	})
}

// BoolVIsNil applies the IsNil predicate on the "bool_v" field.
func BoolVIsNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldBoolV)))
	})
}

// BoolVNotNil applies the NotNil predicate on the "bool_v" field.
func BoolVNotNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldBoolV)))
	})
}

// StrVEQ applies the EQ predicate on the "str_v" field.
func StrVEQ(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStrV), v))
	})
}

// StrVNEQ applies the NEQ predicate on the "str_v" field.
func StrVNEQ(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStrV), v))
	})
}

// StrVIn applies the In predicate on the "str_v" field.
func StrVIn(vs ...string) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStrV), v...))
	})
}

// StrVNotIn applies the NotIn predicate on the "str_v" field.
func StrVNotIn(vs ...string) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStrV), v...))
	})
}

// StrVGT applies the GT predicate on the "str_v" field.
func StrVGT(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStrV), v))
	})
}

// StrVGTE applies the GTE predicate on the "str_v" field.
func StrVGTE(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStrV), v))
	})
}

// StrVLT applies the LT predicate on the "str_v" field.
func StrVLT(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStrV), v))
	})
}

// StrVLTE applies the LTE predicate on the "str_v" field.
func StrVLTE(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStrV), v))
	})
}

// StrVContains applies the Contains predicate on the "str_v" field.
func StrVContains(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStrV), v))
	})
}

// StrVHasPrefix applies the HasPrefix predicate on the "str_v" field.
func StrVHasPrefix(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStrV), v))
	})
}

// StrVHasSuffix applies the HasSuffix predicate on the "str_v" field.
func StrVHasSuffix(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStrV), v))
	})
}

// StrVIsNil applies the IsNil predicate on the "str_v" field.
func StrVIsNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldStrV)))
	})
}

// StrVNotNil applies the NotNil predicate on the "str_v" field.
func StrVNotNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldStrV)))
	})
}

// StrVEqualFold applies the EqualFold predicate on the "str_v" field.
func StrVEqualFold(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStrV), v))
	})
}

// StrVContainsFold applies the ContainsFold predicate on the "str_v" field.
func StrVContainsFold(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStrV), v))
	})
}

// LongVEQ applies the EQ predicate on the "long_v" field.
func LongVEQ(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLongV), v))
	})
}

// LongVNEQ applies the NEQ predicate on the "long_v" field.
func LongVNEQ(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLongV), v))
	})
}

// LongVIn applies the In predicate on the "long_v" field.
func LongVIn(vs ...int64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLongV), v...))
	})
}

// LongVNotIn applies the NotIn predicate on the "long_v" field.
func LongVNotIn(vs ...int64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLongV), v...))
	})
}

// LongVGT applies the GT predicate on the "long_v" field.
func LongVGT(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLongV), v))
	})
}

// LongVGTE applies the GTE predicate on the "long_v" field.
func LongVGTE(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLongV), v))
	})
}

// LongVLT applies the LT predicate on the "long_v" field.
func LongVLT(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLongV), v))
	})
}

// LongVLTE applies the LTE predicate on the "long_v" field.
func LongVLTE(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLongV), v))
	})
}

// LongVIsNil applies the IsNil predicate on the "long_v" field.
func LongVIsNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLongV)))
	})
}

// LongVNotNil applies the NotNil predicate on the "long_v" field.
func LongVNotNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLongV)))
	})
}

// DblVEQ applies the EQ predicate on the "dbl_v" field.
func DblVEQ(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDblV), v))
	})
}

// DblVNEQ applies the NEQ predicate on the "dbl_v" field.
func DblVNEQ(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDblV), v))
	})
}

// DblVIn applies the In predicate on the "dbl_v" field.
func DblVIn(vs ...float64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDblV), v...))
	})
}

// DblVNotIn applies the NotIn predicate on the "dbl_v" field.
func DblVNotIn(vs ...float64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDblV), v...))
	})
}

// DblVGT applies the GT predicate on the "dbl_v" field.
func DblVGT(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDblV), v))
	})
}

// DblVGTE applies the GTE predicate on the "dbl_v" field.
func DblVGTE(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDblV), v))
	})
}

// DblVLT applies the LT predicate on the "dbl_v" field.
func DblVLT(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDblV), v))
	})
}

// DblVLTE applies the LTE predicate on the "dbl_v" field.
func DblVLTE(v float64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDblV), v))
	})
}

// DblVIsNil applies the IsNil predicate on the "dbl_v" field.
func DblVIsNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDblV)))
	})
}

// DblVNotNil applies the NotNil predicate on the "dbl_v" field.
func DblVNotNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDblV)))
	})
}

// JSONVEQ applies the EQ predicate on the "json_v" field.
func JSONVEQ(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJSONV), v))
	})
}

// JSONVNEQ applies the NEQ predicate on the "json_v" field.
func JSONVNEQ(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldJSONV), v))
	})
}

// JSONVIn applies the In predicate on the "json_v" field.
func JSONVIn(vs ...string) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldJSONV), v...))
	})
}

// JSONVNotIn applies the NotIn predicate on the "json_v" field.
func JSONVNotIn(vs ...string) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldJSONV), v...))
	})
}

// JSONVGT applies the GT predicate on the "json_v" field.
func JSONVGT(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldJSONV), v))
	})
}

// JSONVGTE applies the GTE predicate on the "json_v" field.
func JSONVGTE(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldJSONV), v))
	})
}

// JSONVLT applies the LT predicate on the "json_v" field.
func JSONVLT(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldJSONV), v))
	})
}

// JSONVLTE applies the LTE predicate on the "json_v" field.
func JSONVLTE(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldJSONV), v))
	})
}

// JSONVContains applies the Contains predicate on the "json_v" field.
func JSONVContains(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldJSONV), v))
	})
}

// JSONVHasPrefix applies the HasPrefix predicate on the "json_v" field.
func JSONVHasPrefix(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldJSONV), v))
	})
}

// JSONVHasSuffix applies the HasSuffix predicate on the "json_v" field.
func JSONVHasSuffix(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldJSONV), v))
	})
}

// JSONVIsNil applies the IsNil predicate on the "json_v" field.
func JSONVIsNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldJSONV)))
	})
}

// JSONVNotNil applies the NotNil predicate on the "json_v" field.
func JSONVNotNil() predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldJSONV)))
	})
}

// JSONVEqualFold applies the EqualFold predicate on the "json_v" field.
func JSONVEqualFold(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldJSONV), v))
	})
}

// JSONVContainsFold applies the ContainsFold predicate on the "json_v" field.
func JSONVContainsFold(v string) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldJSONV), v))
	})
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTs), v))
	})
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTs), v))
	})
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...int64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTs), v...))
	})
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...int64) predicate.TsKvLatest {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TsKvLatest(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTs), v...))
	})
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTs), v))
	})
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTs), v))
	})
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTs), v))
	})
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v int64) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTs), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TsKvLatest) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TsKvLatest) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TsKvLatest) predicate.TsKvLatest {
	return predicate.TsKvLatest(func(s *sql.Selector) {
		p(s.Not())
	})
}
