// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tsdb-ent-example/ent/attributekv"
	"tsdb-ent-example/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeKVDelete is the builder for deleting a AttributeKV entity.
type AttributeKVDelete struct {
	config
	hooks    []Hook
	mutation *AttributeKVMutation
}

// Where appends a list predicates to the AttributeKVDelete builder.
func (akd *AttributeKVDelete) Where(ps ...predicate.AttributeKV) *AttributeKVDelete {
	akd.mutation.Where(ps...)
	return akd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (akd *AttributeKVDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(akd.hooks) == 0 {
		affected, err = akd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AttributeKVMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			akd.mutation = mutation
			affected, err = akd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(akd.hooks) - 1; i >= 0; i-- {
			if akd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = akd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, akd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (akd *AttributeKVDelete) ExecX(ctx context.Context) int {
	n, err := akd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (akd *AttributeKVDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: attributekv.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: attributekv.FieldID,
			},
		},
	}
	if ps := akd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, akd.driver, _spec)
}

// AttributeKVDeleteOne is the builder for deleting a single AttributeKV entity.
type AttributeKVDeleteOne struct {
	akd *AttributeKVDelete
}

// Exec executes the deletion query.
func (akdo *AttributeKVDeleteOne) Exec(ctx context.Context) error {
	n, err := akdo.akd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attributekv.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (akdo *AttributeKVDeleteOne) ExecX(ctx context.Context) {
	akdo.akd.ExecX(ctx)
}
