// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsdb-ent-example/ent/attributekv"
	"tsdb-ent-example/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeKVQuery is the builder for querying AttributeKV entities.
type AttributeKVQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AttributeKV
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttributeKVQuery builder.
func (akq *AttributeKVQuery) Where(ps ...predicate.AttributeKV) *AttributeKVQuery {
	akq.predicates = append(akq.predicates, ps...)
	return akq
}

// Limit adds a limit step to the query.
func (akq *AttributeKVQuery) Limit(limit int) *AttributeKVQuery {
	akq.limit = &limit
	return akq
}

// Offset adds an offset step to the query.
func (akq *AttributeKVQuery) Offset(offset int) *AttributeKVQuery {
	akq.offset = &offset
	return akq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (akq *AttributeKVQuery) Unique(unique bool) *AttributeKVQuery {
	akq.unique = &unique
	return akq
}

// Order adds an order step to the query.
func (akq *AttributeKVQuery) Order(o ...OrderFunc) *AttributeKVQuery {
	akq.order = append(akq.order, o...)
	return akq
}

// First returns the first AttributeKV entity from the query.
// Returns a *NotFoundError when no AttributeKV was found.
func (akq *AttributeKVQuery) First(ctx context.Context) (*AttributeKV, error) {
	nodes, err := akq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attributekv.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (akq *AttributeKVQuery) FirstX(ctx context.Context) *AttributeKV {
	node, err := akq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AttributeKV ID from the query.
// Returns a *NotFoundError when no AttributeKV ID was found.
func (akq *AttributeKVQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attributekv.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (akq *AttributeKVQuery) FirstIDX(ctx context.Context) int {
	id, err := akq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AttributeKV entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AttributeKV entity is not found.
// Returns a *NotFoundError when no AttributeKV entities are found.
func (akq *AttributeKVQuery) Only(ctx context.Context) (*AttributeKV, error) {
	nodes, err := akq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attributekv.Label}
	default:
		return nil, &NotSingularError{attributekv.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (akq *AttributeKVQuery) OnlyX(ctx context.Context) *AttributeKV {
	node, err := akq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AttributeKV ID in the query.
// Returns a *NotSingularError when exactly one AttributeKV ID is not found.
// Returns a *NotFoundError when no entities are found.
func (akq *AttributeKVQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = &NotSingularError{attributekv.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (akq *AttributeKVQuery) OnlyIDX(ctx context.Context) int {
	id, err := akq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttributeKVs.
func (akq *AttributeKVQuery) All(ctx context.Context) ([]*AttributeKV, error) {
	if err := akq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return akq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (akq *AttributeKVQuery) AllX(ctx context.Context) []*AttributeKV {
	nodes, err := akq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AttributeKV IDs.
func (akq *AttributeKVQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := akq.Select(attributekv.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (akq *AttributeKVQuery) IDsX(ctx context.Context) []int {
	ids, err := akq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (akq *AttributeKVQuery) Count(ctx context.Context) (int, error) {
	if err := akq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return akq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (akq *AttributeKVQuery) CountX(ctx context.Context) int {
	count, err := akq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (akq *AttributeKVQuery) Exist(ctx context.Context) (bool, error) {
	if err := akq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return akq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (akq *AttributeKVQuery) ExistX(ctx context.Context) bool {
	exist, err := akq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttributeKVQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (akq *AttributeKVQuery) Clone() *AttributeKVQuery {
	if akq == nil {
		return nil
	}
	return &AttributeKVQuery{
		config:     akq.config,
		limit:      akq.limit,
		offset:     akq.offset,
		order:      append([]OrderFunc{}, akq.order...),
		predicates: append([]predicate.AttributeKV{}, akq.predicates...),
		// clone intermediate query.
		sql:  akq.sql.Clone(),
		path: akq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EntityType string `json:"entity_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AttributeKV.Query().
//		GroupBy(attributekv.FieldEntityType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (akq *AttributeKVQuery) GroupBy(field string, fields ...string) *AttributeKVGroupBy {
	group := &AttributeKVGroupBy{config: akq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := akq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return akq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EntityType string `json:"entity_type,omitempty"`
//	}
//
//	client.AttributeKV.Query().
//		Select(attributekv.FieldEntityType).
//		Scan(ctx, &v)
//
func (akq *AttributeKVQuery) Select(fields ...string) *AttributeKVSelect {
	akq.fields = append(akq.fields, fields...)
	return &AttributeKVSelect{AttributeKVQuery: akq}
}

func (akq *AttributeKVQuery) prepareQuery(ctx context.Context) error {
	for _, f := range akq.fields {
		if !attributekv.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if akq.path != nil {
		prev, err := akq.path(ctx)
		if err != nil {
			return err
		}
		akq.sql = prev
	}
	return nil
}

func (akq *AttributeKVQuery) sqlAll(ctx context.Context) ([]*AttributeKV, error) {
	var (
		nodes = []*AttributeKV{}
		_spec = akq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AttributeKV{config: akq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(akq.modifiers) > 0 {
		_spec.Modifiers = akq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, akq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (akq *AttributeKVQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := akq.querySpec()
	if len(akq.modifiers) > 0 {
		_spec.Modifiers = akq.modifiers
	}
	_spec.Node.Columns = akq.fields
	if len(akq.fields) > 0 {
		_spec.Unique = akq.unique != nil && *akq.unique
	}
	return sqlgraph.CountNodes(ctx, akq.driver, _spec)
}

func (akq *AttributeKVQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := akq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (akq *AttributeKVQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   attributekv.Table,
			Columns: attributekv.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: attributekv.FieldID,
			},
		},
		From:   akq.sql,
		Unique: true,
	}
	if unique := akq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := akq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attributekv.FieldID)
		for i := range fields {
			if fields[i] != attributekv.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := akq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := akq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := akq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := akq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (akq *AttributeKVQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(akq.driver.Dialect())
	t1 := builder.Table(attributekv.Table)
	columns := akq.fields
	if len(columns) == 0 {
		columns = attributekv.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if akq.sql != nil {
		selector = akq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if akq.unique != nil && *akq.unique {
		selector.Distinct()
	}
	for _, m := range akq.modifiers {
		m(selector)
	}
	for _, p := range akq.predicates {
		p(selector)
	}
	for _, p := range akq.order {
		p(selector)
	}
	if offset := akq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := akq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (akq *AttributeKVQuery) Modify(modifiers ...func(s *sql.Selector)) *AttributeKVSelect {
	akq.modifiers = append(akq.modifiers, modifiers...)
	return akq.Select()
}

// AttributeKVGroupBy is the group-by builder for AttributeKV entities.
type AttributeKVGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (akgb *AttributeKVGroupBy) Aggregate(fns ...AggregateFunc) *AttributeKVGroupBy {
	akgb.fns = append(akgb.fns, fns...)
	return akgb
}

// Scan applies the group-by query and scans the result into the given value.
func (akgb *AttributeKVGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := akgb.path(ctx)
	if err != nil {
		return err
	}
	akgb.sql = query
	return akgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := akgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AttributeKVGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) StringsX(ctx context.Context) []string {
	v, err := akgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = akgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) StringX(ctx context.Context) string {
	v, err := akgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AttributeKVGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) IntsX(ctx context.Context) []int {
	v, err := akgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = akgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) IntX(ctx context.Context) int {
	v, err := akgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AttributeKVGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := akgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = akgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) Float64X(ctx context.Context) float64 {
	v, err := akgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(akgb.fields) > 1 {
		return nil, errors.New("ent: AttributeKVGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := akgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := akgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (akgb *AttributeKVGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = akgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (akgb *AttributeKVGroupBy) BoolX(ctx context.Context) bool {
	v, err := akgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (akgb *AttributeKVGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range akgb.fields {
		if !attributekv.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := akgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := akgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (akgb *AttributeKVGroupBy) sqlQuery() *sql.Selector {
	selector := akgb.sql.Select()
	aggregation := make([]string, 0, len(akgb.fns))
	for _, fn := range akgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(akgb.fields)+len(akgb.fns))
		for _, f := range akgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(akgb.fields...)...)
}

// AttributeKVSelect is the builder for selecting fields of AttributeKV entities.
type AttributeKVSelect struct {
	*AttributeKVQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aks *AttributeKVSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aks.prepareQuery(ctx); err != nil {
		return err
	}
	aks.sql = aks.AttributeKVQuery.sqlQuery(ctx)
	return aks.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aks *AttributeKVSelect) ScanX(ctx context.Context, v interface{}) {
	if err := aks.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Strings(ctx context.Context) ([]string, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AttributeKVSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aks *AttributeKVSelect) StringsX(ctx context.Context) []string {
	v, err := aks.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aks.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aks *AttributeKVSelect) StringX(ctx context.Context) string {
	v, err := aks.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Ints(ctx context.Context) ([]int, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AttributeKVSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aks *AttributeKVSelect) IntsX(ctx context.Context) []int {
	v, err := aks.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aks.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aks *AttributeKVSelect) IntX(ctx context.Context) int {
	v, err := aks.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AttributeKVSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aks *AttributeKVSelect) Float64sX(ctx context.Context) []float64 {
	v, err := aks.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aks.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aks *AttributeKVSelect) Float64X(ctx context.Context) float64 {
	v, err := aks.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aks.fields) > 1 {
		return nil, errors.New("ent: AttributeKVSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aks *AttributeKVSelect) BoolsX(ctx context.Context) []bool {
	v, err := aks.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aks *AttributeKVSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aks.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{attributekv.Label}
	default:
		err = fmt.Errorf("ent: AttributeKVSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aks *AttributeKVSelect) BoolX(ctx context.Context) bool {
	v, err := aks.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aks *AttributeKVSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aks.sql.Query()
	if err := aks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (aks *AttributeKVSelect) Modify(modifiers ...func(s *sql.Selector)) *AttributeKVSelect {
	aks.modifiers = append(aks.modifiers, modifiers...)
	return aks
}
