// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskvdictionary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TsKvDictionaryDelete is the builder for deleting a TsKvDictionary entity.
type TsKvDictionaryDelete struct {
	config
	hooks    []Hook
	mutation *TsKvDictionaryMutation
}

// Where appends a list predicates to the TsKvDictionaryDelete builder.
func (tkdd *TsKvDictionaryDelete) Where(ps ...predicate.TsKvDictionary) *TsKvDictionaryDelete {
	tkdd.mutation.Where(ps...)
	return tkdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tkdd *TsKvDictionaryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tkdd.hooks) == 0 {
		affected, err = tkdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TsKvDictionaryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tkdd.mutation = mutation
			affected, err = tkdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tkdd.hooks) - 1; i >= 0; i-- {
			if tkdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tkdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tkdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tkdd *TsKvDictionaryDelete) ExecX(ctx context.Context) int {
	n, err := tkdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tkdd *TsKvDictionaryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tskvdictionary.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvdictionary.FieldID,
			},
		},
	}
	if ps := tkdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tkdd.driver, _spec)
}

// TsKvDictionaryDeleteOne is the builder for deleting a single TsKvDictionary entity.
type TsKvDictionaryDeleteOne struct {
	tkdd *TsKvDictionaryDelete
}

// Exec executes the deletion query.
func (tkddo *TsKvDictionaryDeleteOne) Exec(ctx context.Context) error {
	n, err := tkddo.tkdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tskvdictionary.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tkddo *TsKvDictionaryDeleteOne) ExecX(ctx context.Context) {
	tkddo.tkdd.ExecX(ctx)
}
