// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tsdb-ent-example/ent/tskvlatest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TsKvLatestCreate is the builder for creating a TsKvLatest entity.
type TsKvLatestCreate struct {
	config
	mutation *TsKvLatestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntityID sets the "entity_id" field.
func (tklc *TsKvLatestCreate) SetEntityID(u uuid.UUID) *TsKvLatestCreate {
	tklc.mutation.SetEntityID(u)
	return tklc
}

// SetKey sets the "key" field.
func (tklc *TsKvLatestCreate) SetKey(i int) *TsKvLatestCreate {
	tklc.mutation.SetKey(i)
	return tklc
}

// SetBoolV sets the "bool_v" field.
func (tklc *TsKvLatestCreate) SetBoolV(b bool) *TsKvLatestCreate {
	tklc.mutation.SetBoolV(b)
	return tklc
}

// SetNillableBoolV sets the "bool_v" field if the given value is not nil.
func (tklc *TsKvLatestCreate) SetNillableBoolV(b *bool) *TsKvLatestCreate {
	if b != nil {
		tklc.SetBoolV(*b)
	}
	return tklc
}

// SetStrV sets the "str_v" field.
func (tklc *TsKvLatestCreate) SetStrV(s string) *TsKvLatestCreate {
	tklc.mutation.SetStrV(s)
	return tklc
}

// SetNillableStrV sets the "str_v" field if the given value is not nil.
func (tklc *TsKvLatestCreate) SetNillableStrV(s *string) *TsKvLatestCreate {
	if s != nil {
		tklc.SetStrV(*s)
	}
	return tklc
}

// SetLongV sets the "long_v" field.
func (tklc *TsKvLatestCreate) SetLongV(i int64) *TsKvLatestCreate {
	tklc.mutation.SetLongV(i)
	return tklc
}

// SetNillableLongV sets the "long_v" field if the given value is not nil.
func (tklc *TsKvLatestCreate) SetNillableLongV(i *int64) *TsKvLatestCreate {
	if i != nil {
		tklc.SetLongV(*i)
	}
	return tklc
}

// SetDblV sets the "dbl_v" field.
func (tklc *TsKvLatestCreate) SetDblV(f float64) *TsKvLatestCreate {
	tklc.mutation.SetDblV(f)
	return tklc
}

// SetNillableDblV sets the "dbl_v" field if the given value is not nil.
func (tklc *TsKvLatestCreate) SetNillableDblV(f *float64) *TsKvLatestCreate {
	if f != nil {
		tklc.SetDblV(*f)
	}
	return tklc
}

// SetJSONV sets the "json_v" field.
func (tklc *TsKvLatestCreate) SetJSONV(s string) *TsKvLatestCreate {
	tklc.mutation.SetJSONV(s)
	return tklc
}

// SetNillableJSONV sets the "json_v" field if the given value is not nil.
func (tklc *TsKvLatestCreate) SetNillableJSONV(s *string) *TsKvLatestCreate {
	if s != nil {
		tklc.SetJSONV(*s)
	}
	return tklc
}

// SetTs sets the "ts" field.
func (tklc *TsKvLatestCreate) SetTs(i int64) *TsKvLatestCreate {
	tklc.mutation.SetTs(i)
	return tklc
}

// Mutation returns the TsKvLatestMutation object of the builder.
func (tklc *TsKvLatestCreate) Mutation() *TsKvLatestMutation {
	return tklc.mutation
}

// Save creates the TsKvLatest in the database.
func (tklc *TsKvLatestCreate) Save(ctx context.Context) (*TsKvLatest, error) {
	var (
		err  error
		node *TsKvLatest
	)
	if len(tklc.hooks) == 0 {
		if err = tklc.check(); err != nil {
			return nil, err
		}
		node, err = tklc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TsKvLatestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tklc.check(); err != nil {
				return nil, err
			}
			tklc.mutation = mutation
			if node, err = tklc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tklc.hooks) - 1; i >= 0; i-- {
			if tklc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tklc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tklc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tklc *TsKvLatestCreate) SaveX(ctx context.Context) *TsKvLatest {
	v, err := tklc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tklc *TsKvLatestCreate) Exec(ctx context.Context) error {
	_, err := tklc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tklc *TsKvLatestCreate) ExecX(ctx context.Context) {
	if err := tklc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tklc *TsKvLatestCreate) check() error {
	if _, ok := tklc.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "TsKvLatest.entity_id"`)}
	}
	if _, ok := tklc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "TsKvLatest.key"`)}
	}
	if v, ok := tklc.mutation.StrV(); ok {
		if err := tskvlatest.StrVValidator(v); err != nil {
			return &ValidationError{Name: "str_v", err: fmt.Errorf(`ent: validator failed for field "TsKvLatest.str_v": %w`, err)}
		}
	}
	if _, ok := tklc.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "TsKvLatest.ts"`)}
	}
	return nil
}

func (tklc *TsKvLatestCreate) sqlSave(ctx context.Context) (*TsKvLatest, error) {
	_node, _spec := tklc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tklc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tklc *TsKvLatestCreate) createSpec() (*TsKvLatest, *sqlgraph.CreateSpec) {
	var (
		_node = &TsKvLatest{config: tklc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tskvlatest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvlatest.FieldID,
			},
		}
	)
	_spec.OnConflict = tklc.conflict
	if value, ok := tklc.mutation.EntityID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: tskvlatest.FieldEntityID,
		})
		_node.EntityID = value
	}
	if value, ok := tklc.mutation.Key(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tskvlatest.FieldKey,
		})
		_node.Key = value
	}
	if value, ok := tklc.mutation.BoolV(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tskvlatest.FieldBoolV,
		})
		_node.BoolV = &value
	}
	if value, ok := tklc.mutation.StrV(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldStrV,
		})
		_node.StrV = &value
	}
	if value, ok := tklc.mutation.LongV(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldLongV,
		})
		_node.LongV = &value
	}
	if value, ok := tklc.mutation.DblV(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: tskvlatest.FieldDblV,
		})
		_node.DblV = &value
	}
	if value, ok := tklc.mutation.JSONV(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldJSONV,
		})
		_node.JSONV = &value
	}
	if value, ok := tklc.mutation.Ts(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldTs,
		})
		_node.Ts = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TsKvLatest.Create().
//		SetEntityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TsKvLatestUpsert) {
//			SetEntityID(v+v).
//		}).
//		Exec(ctx)
//
func (tklc *TsKvLatestCreate) OnConflict(opts ...sql.ConflictOption) *TsKvLatestUpsertOne {
	tklc.conflict = opts
	return &TsKvLatestUpsertOne{
		create: tklc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TsKvLatest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tklc *TsKvLatestCreate) OnConflictColumns(columns ...string) *TsKvLatestUpsertOne {
	tklc.conflict = append(tklc.conflict, sql.ConflictColumns(columns...))
	return &TsKvLatestUpsertOne{
		create: tklc,
	}
}

type (
	// TsKvLatestUpsertOne is the builder for "upsert"-ing
	//  one TsKvLatest node.
	TsKvLatestUpsertOne struct {
		create *TsKvLatestCreate
	}

	// TsKvLatestUpsert is the "OnConflict" setter.
	TsKvLatestUpsert struct {
		*sql.UpdateSet
	}
)

// SetEntityID sets the "entity_id" field.
func (u *TsKvLatestUpsert) SetEntityID(v uuid.UUID) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldEntityID, v)
	return u
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateEntityID() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldEntityID)
	return u
}

// SetKey sets the "key" field.
func (u *TsKvLatestUpsert) SetKey(v int) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateKey() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldKey)
	return u
}

// AddKey adds v to the "key" field.
func (u *TsKvLatestUpsert) AddKey(v int) *TsKvLatestUpsert {
	u.Add(tskvlatest.FieldKey, v)
	return u
}

// SetBoolV sets the "bool_v" field.
func (u *TsKvLatestUpsert) SetBoolV(v bool) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldBoolV, v)
	return u
}

// UpdateBoolV sets the "bool_v" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateBoolV() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldBoolV)
	return u
}

// ClearBoolV clears the value of the "bool_v" field.
func (u *TsKvLatestUpsert) ClearBoolV() *TsKvLatestUpsert {
	u.SetNull(tskvlatest.FieldBoolV)
	return u
}

// SetStrV sets the "str_v" field.
func (u *TsKvLatestUpsert) SetStrV(v string) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldStrV, v)
	return u
}

// UpdateStrV sets the "str_v" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateStrV() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldStrV)
	return u
}

// ClearStrV clears the value of the "str_v" field.
func (u *TsKvLatestUpsert) ClearStrV() *TsKvLatestUpsert {
	u.SetNull(tskvlatest.FieldStrV)
	return u
}

// SetLongV sets the "long_v" field.
func (u *TsKvLatestUpsert) SetLongV(v int64) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldLongV, v)
	return u
}

// UpdateLongV sets the "long_v" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateLongV() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldLongV)
	return u
}

// AddLongV adds v to the "long_v" field.
func (u *TsKvLatestUpsert) AddLongV(v int64) *TsKvLatestUpsert {
	u.Add(tskvlatest.FieldLongV, v)
	return u
}

// ClearLongV clears the value of the "long_v" field.
func (u *TsKvLatestUpsert) ClearLongV() *TsKvLatestUpsert {
	u.SetNull(tskvlatest.FieldLongV)
	return u
}

// SetDblV sets the "dbl_v" field.
func (u *TsKvLatestUpsert) SetDblV(v float64) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldDblV, v)
	return u
}

// UpdateDblV sets the "dbl_v" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateDblV() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldDblV)
	return u
}

// AddDblV adds v to the "dbl_v" field.
func (u *TsKvLatestUpsert) AddDblV(v float64) *TsKvLatestUpsert {
	u.Add(tskvlatest.FieldDblV, v)
	return u
}

// ClearDblV clears the value of the "dbl_v" field.
func (u *TsKvLatestUpsert) ClearDblV() *TsKvLatestUpsert {
	u.SetNull(tskvlatest.FieldDblV)
	return u
}

// SetJSONV sets the "json_v" field.
func (u *TsKvLatestUpsert) SetJSONV(v string) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldJSONV, v)
	return u
}

// UpdateJSONV sets the "json_v" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateJSONV() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldJSONV)
	return u
}

// ClearJSONV clears the value of the "json_v" field.
func (u *TsKvLatestUpsert) ClearJSONV() *TsKvLatestUpsert {
	u.SetNull(tskvlatest.FieldJSONV)
	return u
}

// SetTs sets the "ts" field.
func (u *TsKvLatestUpsert) SetTs(v int64) *TsKvLatestUpsert {
	u.Set(tskvlatest.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *TsKvLatestUpsert) UpdateTs() *TsKvLatestUpsert {
	u.SetExcluded(tskvlatest.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *TsKvLatestUpsert) AddTs(v int64) *TsKvLatestUpsert {
	u.Add(tskvlatest.FieldTs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TsKvLatest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *TsKvLatestUpsertOne) UpdateNewValues() *TsKvLatestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.TsKvLatest.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *TsKvLatestUpsertOne) Ignore() *TsKvLatestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TsKvLatestUpsertOne) DoNothing() *TsKvLatestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TsKvLatestCreate.OnConflict
// documentation for more info.
func (u *TsKvLatestUpsertOne) Update(set func(*TsKvLatestUpsert)) *TsKvLatestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TsKvLatestUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *TsKvLatestUpsertOne) SetEntityID(v uuid.UUID) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateEntityID() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateEntityID()
	})
}

// SetKey sets the "key" field.
func (u *TsKvLatestUpsertOne) SetKey(v int) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetKey(v)
	})
}

// AddKey adds v to the "key" field.
func (u *TsKvLatestUpsertOne) AddKey(v int) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateKey() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateKey()
	})
}

// SetBoolV sets the "bool_v" field.
func (u *TsKvLatestUpsertOne) SetBoolV(v bool) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetBoolV(v)
	})
}

// UpdateBoolV sets the "bool_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateBoolV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateBoolV()
	})
}

// ClearBoolV clears the value of the "bool_v" field.
func (u *TsKvLatestUpsertOne) ClearBoolV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearBoolV()
	})
}

// SetStrV sets the "str_v" field.
func (u *TsKvLatestUpsertOne) SetStrV(v string) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetStrV(v)
	})
}

// UpdateStrV sets the "str_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateStrV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateStrV()
	})
}

// ClearStrV clears the value of the "str_v" field.
func (u *TsKvLatestUpsertOne) ClearStrV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearStrV()
	})
}

// SetLongV sets the "long_v" field.
func (u *TsKvLatestUpsertOne) SetLongV(v int64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetLongV(v)
	})
}

// AddLongV adds v to the "long_v" field.
func (u *TsKvLatestUpsertOne) AddLongV(v int64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddLongV(v)
	})
}

// UpdateLongV sets the "long_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateLongV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateLongV()
	})
}

// ClearLongV clears the value of the "long_v" field.
func (u *TsKvLatestUpsertOne) ClearLongV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearLongV()
	})
}

// SetDblV sets the "dbl_v" field.
func (u *TsKvLatestUpsertOne) SetDblV(v float64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetDblV(v)
	})
}

// AddDblV adds v to the "dbl_v" field.
func (u *TsKvLatestUpsertOne) AddDblV(v float64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddDblV(v)
	})
}

// UpdateDblV sets the "dbl_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateDblV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateDblV()
	})
}

// ClearDblV clears the value of the "dbl_v" field.
func (u *TsKvLatestUpsertOne) ClearDblV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearDblV()
	})
}

// SetJSONV sets the "json_v" field.
func (u *TsKvLatestUpsertOne) SetJSONV(v string) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetJSONV(v)
	})
}

// UpdateJSONV sets the "json_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateJSONV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateJSONV()
	})
}

// ClearJSONV clears the value of the "json_v" field.
func (u *TsKvLatestUpsertOne) ClearJSONV() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearJSONV()
	})
}

// SetTs sets the "ts" field.
func (u *TsKvLatestUpsertOne) SetTs(v int64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *TsKvLatestUpsertOne) AddTs(v int64) *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *TsKvLatestUpsertOne) UpdateTs() *TsKvLatestUpsertOne {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *TsKvLatestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TsKvLatestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TsKvLatestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TsKvLatestUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TsKvLatestUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TsKvLatestCreateBulk is the builder for creating many TsKvLatest entities in bulk.
type TsKvLatestCreateBulk struct {
	config
	builders []*TsKvLatestCreate
	conflict []sql.ConflictOption
}

// Save creates the TsKvLatest entities in the database.
func (tklcb *TsKvLatestCreateBulk) Save(ctx context.Context) ([]*TsKvLatest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tklcb.builders))
	nodes := make([]*TsKvLatest, len(tklcb.builders))
	mutators := make([]Mutator, len(tklcb.builders))
	for i := range tklcb.builders {
		func(i int, root context.Context) {
			builder := tklcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TsKvLatestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tklcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tklcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tklcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tklcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tklcb *TsKvLatestCreateBulk) SaveX(ctx context.Context) []*TsKvLatest {
	v, err := tklcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tklcb *TsKvLatestCreateBulk) Exec(ctx context.Context) error {
	_, err := tklcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tklcb *TsKvLatestCreateBulk) ExecX(ctx context.Context) {
	if err := tklcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TsKvLatest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TsKvLatestUpsert) {
//			SetEntityID(v+v).
//		}).
//		Exec(ctx)
//
func (tklcb *TsKvLatestCreateBulk) OnConflict(opts ...sql.ConflictOption) *TsKvLatestUpsertBulk {
	tklcb.conflict = opts
	return &TsKvLatestUpsertBulk{
		create: tklcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TsKvLatest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tklcb *TsKvLatestCreateBulk) OnConflictColumns(columns ...string) *TsKvLatestUpsertBulk {
	tklcb.conflict = append(tklcb.conflict, sql.ConflictColumns(columns...))
	return &TsKvLatestUpsertBulk{
		create: tklcb,
	}
}

// TsKvLatestUpsertBulk is the builder for "upsert"-ing
// a bulk of TsKvLatest nodes.
type TsKvLatestUpsertBulk struct {
	create *TsKvLatestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TsKvLatest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *TsKvLatestUpsertBulk) UpdateNewValues() *TsKvLatestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TsKvLatest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *TsKvLatestUpsertBulk) Ignore() *TsKvLatestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TsKvLatestUpsertBulk) DoNothing() *TsKvLatestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TsKvLatestCreateBulk.OnConflict
// documentation for more info.
func (u *TsKvLatestUpsertBulk) Update(set func(*TsKvLatestUpsert)) *TsKvLatestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TsKvLatestUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntityID sets the "entity_id" field.
func (u *TsKvLatestUpsertBulk) SetEntityID(v uuid.UUID) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetEntityID(v)
	})
}

// UpdateEntityID sets the "entity_id" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateEntityID() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateEntityID()
	})
}

// SetKey sets the "key" field.
func (u *TsKvLatestUpsertBulk) SetKey(v int) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetKey(v)
	})
}

// AddKey adds v to the "key" field.
func (u *TsKvLatestUpsertBulk) AddKey(v int) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateKey() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateKey()
	})
}

// SetBoolV sets the "bool_v" field.
func (u *TsKvLatestUpsertBulk) SetBoolV(v bool) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetBoolV(v)
	})
}

// UpdateBoolV sets the "bool_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateBoolV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateBoolV()
	})
}

// ClearBoolV clears the value of the "bool_v" field.
func (u *TsKvLatestUpsertBulk) ClearBoolV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearBoolV()
	})
}

// SetStrV sets the "str_v" field.
func (u *TsKvLatestUpsertBulk) SetStrV(v string) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetStrV(v)
	})
}

// UpdateStrV sets the "str_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateStrV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateStrV()
	})
}

// ClearStrV clears the value of the "str_v" field.
func (u *TsKvLatestUpsertBulk) ClearStrV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearStrV()
	})
}

// SetLongV sets the "long_v" field.
func (u *TsKvLatestUpsertBulk) SetLongV(v int64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetLongV(v)
	})
}

// AddLongV adds v to the "long_v" field.
func (u *TsKvLatestUpsertBulk) AddLongV(v int64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddLongV(v)
	})
}

// UpdateLongV sets the "long_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateLongV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateLongV()
	})
}

// ClearLongV clears the value of the "long_v" field.
func (u *TsKvLatestUpsertBulk) ClearLongV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearLongV()
	})
}

// SetDblV sets the "dbl_v" field.
func (u *TsKvLatestUpsertBulk) SetDblV(v float64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetDblV(v)
	})
}

// AddDblV adds v to the "dbl_v" field.
func (u *TsKvLatestUpsertBulk) AddDblV(v float64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddDblV(v)
	})
}

// UpdateDblV sets the "dbl_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateDblV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateDblV()
	})
}

// ClearDblV clears the value of the "dbl_v" field.
func (u *TsKvLatestUpsertBulk) ClearDblV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearDblV()
	})
}

// SetJSONV sets the "json_v" field.
func (u *TsKvLatestUpsertBulk) SetJSONV(v string) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetJSONV(v)
	})
}

// UpdateJSONV sets the "json_v" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateJSONV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateJSONV()
	})
}

// ClearJSONV clears the value of the "json_v" field.
func (u *TsKvLatestUpsertBulk) ClearJSONV() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.ClearJSONV()
	})
}

// SetTs sets the "ts" field.
func (u *TsKvLatestUpsertBulk) SetTs(v int64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *TsKvLatestUpsertBulk) AddTs(v int64) *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *TsKvLatestUpsertBulk) UpdateTs() *TsKvLatestUpsertBulk {
	return u.Update(func(s *TsKvLatestUpsert) {
		s.UpdateTs()
	})
}

// Exec executes the query.
func (u *TsKvLatestUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TsKvLatestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TsKvLatestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TsKvLatestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
