// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskvdictionary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TsKvDictionaryQuery is the builder for querying TsKvDictionary entities.
type TsKvDictionaryQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TsKvDictionary
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TsKvDictionaryQuery builder.
func (tkdq *TsKvDictionaryQuery) Where(ps ...predicate.TsKvDictionary) *TsKvDictionaryQuery {
	tkdq.predicates = append(tkdq.predicates, ps...)
	return tkdq
}

// Limit adds a limit step to the query.
func (tkdq *TsKvDictionaryQuery) Limit(limit int) *TsKvDictionaryQuery {
	tkdq.limit = &limit
	return tkdq
}

// Offset adds an offset step to the query.
func (tkdq *TsKvDictionaryQuery) Offset(offset int) *TsKvDictionaryQuery {
	tkdq.offset = &offset
	return tkdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tkdq *TsKvDictionaryQuery) Unique(unique bool) *TsKvDictionaryQuery {
	tkdq.unique = &unique
	return tkdq
}

// Order adds an order step to the query.
func (tkdq *TsKvDictionaryQuery) Order(o ...OrderFunc) *TsKvDictionaryQuery {
	tkdq.order = append(tkdq.order, o...)
	return tkdq
}

// First returns the first TsKvDictionary entity from the query.
// Returns a *NotFoundError when no TsKvDictionary was found.
func (tkdq *TsKvDictionaryQuery) First(ctx context.Context) (*TsKvDictionary, error) {
	nodes, err := tkdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tskvdictionary.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) FirstX(ctx context.Context) *TsKvDictionary {
	node, err := tkdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TsKvDictionary ID from the query.
// Returns a *NotFoundError when no TsKvDictionary ID was found.
func (tkdq *TsKvDictionaryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tkdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tskvdictionary.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) FirstIDX(ctx context.Context) int {
	id, err := tkdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TsKvDictionary entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TsKvDictionary entity is not found.
// Returns a *NotFoundError when no TsKvDictionary entities are found.
func (tkdq *TsKvDictionaryQuery) Only(ctx context.Context) (*TsKvDictionary, error) {
	nodes, err := tkdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tskvdictionary.Label}
	default:
		return nil, &NotSingularError{tskvdictionary.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) OnlyX(ctx context.Context) *TsKvDictionary {
	node, err := tkdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TsKvDictionary ID in the query.
// Returns a *NotSingularError when exactly one TsKvDictionary ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tkdq *TsKvDictionaryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tkdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = &NotSingularError{tskvdictionary.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) OnlyIDX(ctx context.Context) int {
	id, err := tkdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TsKvDictionaries.
func (tkdq *TsKvDictionaryQuery) All(ctx context.Context) ([]*TsKvDictionary, error) {
	if err := tkdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tkdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) AllX(ctx context.Context) []*TsKvDictionary {
	nodes, err := tkdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TsKvDictionary IDs.
func (tkdq *TsKvDictionaryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tkdq.Select(tskvdictionary.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) IDsX(ctx context.Context) []int {
	ids, err := tkdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tkdq *TsKvDictionaryQuery) Count(ctx context.Context) (int, error) {
	if err := tkdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tkdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) CountX(ctx context.Context) int {
	count, err := tkdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tkdq *TsKvDictionaryQuery) Exist(ctx context.Context) (bool, error) {
	if err := tkdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tkdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tkdq *TsKvDictionaryQuery) ExistX(ctx context.Context) bool {
	exist, err := tkdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TsKvDictionaryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tkdq *TsKvDictionaryQuery) Clone() *TsKvDictionaryQuery {
	if tkdq == nil {
		return nil
	}
	return &TsKvDictionaryQuery{
		config:     tkdq.config,
		limit:      tkdq.limit,
		offset:     tkdq.offset,
		order:      append([]OrderFunc{}, tkdq.order...),
		predicates: append([]predicate.TsKvDictionary{}, tkdq.predicates...),
		// clone intermediate query.
		sql:  tkdq.sql.Clone(),
		path: tkdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TsKvDictionary.Query().
//		GroupBy(tskvdictionary.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tkdq *TsKvDictionaryQuery) GroupBy(field string, fields ...string) *TsKvDictionaryGroupBy {
	group := &TsKvDictionaryGroupBy{config: tkdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tkdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tkdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.TsKvDictionary.Query().
//		Select(tskvdictionary.FieldKey).
//		Scan(ctx, &v)
//
func (tkdq *TsKvDictionaryQuery) Select(fields ...string) *TsKvDictionarySelect {
	tkdq.fields = append(tkdq.fields, fields...)
	return &TsKvDictionarySelect{TsKvDictionaryQuery: tkdq}
}

func (tkdq *TsKvDictionaryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tkdq.fields {
		if !tskvdictionary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tkdq.path != nil {
		prev, err := tkdq.path(ctx)
		if err != nil {
			return err
		}
		tkdq.sql = prev
	}
	return nil
}

func (tkdq *TsKvDictionaryQuery) sqlAll(ctx context.Context) ([]*TsKvDictionary, error) {
	var (
		nodes = []*TsKvDictionary{}
		_spec = tkdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TsKvDictionary{config: tkdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(tkdq.modifiers) > 0 {
		_spec.Modifiers = tkdq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, tkdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tkdq *TsKvDictionaryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tkdq.querySpec()
	if len(tkdq.modifiers) > 0 {
		_spec.Modifiers = tkdq.modifiers
	}
	_spec.Node.Columns = tkdq.fields
	if len(tkdq.fields) > 0 {
		_spec.Unique = tkdq.unique != nil && *tkdq.unique
	}
	return sqlgraph.CountNodes(ctx, tkdq.driver, _spec)
}

func (tkdq *TsKvDictionaryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tkdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tkdq *TsKvDictionaryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tskvdictionary.Table,
			Columns: tskvdictionary.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvdictionary.FieldID,
			},
		},
		From:   tkdq.sql,
		Unique: true,
	}
	if unique := tkdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tkdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tskvdictionary.FieldID)
		for i := range fields {
			if fields[i] != tskvdictionary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tkdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tkdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tkdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tkdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tkdq *TsKvDictionaryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tkdq.driver.Dialect())
	t1 := builder.Table(tskvdictionary.Table)
	columns := tkdq.fields
	if len(columns) == 0 {
		columns = tskvdictionary.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tkdq.sql != nil {
		selector = tkdq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tkdq.unique != nil && *tkdq.unique {
		selector.Distinct()
	}
	for _, m := range tkdq.modifiers {
		m(selector)
	}
	for _, p := range tkdq.predicates {
		p(selector)
	}
	for _, p := range tkdq.order {
		p(selector)
	}
	if offset := tkdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tkdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tkdq *TsKvDictionaryQuery) Modify(modifiers ...func(s *sql.Selector)) *TsKvDictionarySelect {
	tkdq.modifiers = append(tkdq.modifiers, modifiers...)
	return tkdq.Select()
}

// TsKvDictionaryGroupBy is the group-by builder for TsKvDictionary entities.
type TsKvDictionaryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tkdgb *TsKvDictionaryGroupBy) Aggregate(fns ...AggregateFunc) *TsKvDictionaryGroupBy {
	tkdgb.fns = append(tkdgb.fns, fns...)
	return tkdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tkdgb *TsKvDictionaryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tkdgb.path(ctx)
	if err != nil {
		return err
	}
	tkdgb.sql = query
	return tkdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tkdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tkdgb.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionaryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tkdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) StringsX(ctx context.Context) []string {
	v, err := tkdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tkdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionaryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) StringX(ctx context.Context) string {
	v, err := tkdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tkdgb.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionaryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tkdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) IntsX(ctx context.Context) []int {
	v, err := tkdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tkdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionaryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) IntX(ctx context.Context) int {
	v, err := tkdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tkdgb.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionaryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tkdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tkdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tkdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionaryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tkdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tkdgb.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionaryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tkdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tkdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkdgb *TsKvDictionaryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tkdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionaryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tkdgb *TsKvDictionaryGroupBy) BoolX(ctx context.Context) bool {
	v, err := tkdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tkdgb *TsKvDictionaryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tkdgb.fields {
		if !tskvdictionary.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tkdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tkdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tkdgb *TsKvDictionaryGroupBy) sqlQuery() *sql.Selector {
	selector := tkdgb.sql.Select()
	aggregation := make([]string, 0, len(tkdgb.fns))
	for _, fn := range tkdgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tkdgb.fields)+len(tkdgb.fns))
		for _, f := range tkdgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tkdgb.fields...)...)
}

// TsKvDictionarySelect is the builder for selecting fields of TsKvDictionary entities.
type TsKvDictionarySelect struct {
	*TsKvDictionaryQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tkds *TsKvDictionarySelect) Scan(ctx context.Context, v interface{}) error {
	if err := tkds.prepareQuery(ctx); err != nil {
		return err
	}
	tkds.sql = tkds.TsKvDictionaryQuery.sqlQuery(ctx)
	return tkds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) ScanX(ctx context.Context, v interface{}) {
	if err := tkds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Strings(ctx context.Context) ([]string, error) {
	if len(tkds.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionarySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tkds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) StringsX(ctx context.Context) []string {
	v, err := tkds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tkds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionarySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) StringX(ctx context.Context) string {
	v, err := tkds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Ints(ctx context.Context) ([]int, error) {
	if len(tkds.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionarySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tkds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) IntsX(ctx context.Context) []int {
	v, err := tkds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tkds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionarySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) IntX(ctx context.Context) int {
	v, err := tkds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tkds.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionarySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tkds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) Float64sX(ctx context.Context) []float64 {
	v, err := tkds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tkds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionarySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) Float64X(ctx context.Context) float64 {
	v, err := tkds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tkds.fields) > 1 {
		return nil, errors.New("ent: TsKvDictionarySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tkds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) BoolsX(ctx context.Context) []bool {
	v, err := tkds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tkds *TsKvDictionarySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tkds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvdictionary.Label}
	default:
		err = fmt.Errorf("ent: TsKvDictionarySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tkds *TsKvDictionarySelect) BoolX(ctx context.Context) bool {
	v, err := tkds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tkds *TsKvDictionarySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tkds.sql.Query()
	if err := tkds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tkds *TsKvDictionarySelect) Modify(modifiers ...func(s *sql.Selector)) *TsKvDictionarySelect {
	tkds.modifiers = append(tkds.modifiers, modifiers...)
	return tkds
}
