// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"tsdb-ent-example/ent/tskv"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TsKv is the model entity for the TsKv schema.
type TsKv struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	// 实体ID
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// Key holds the value of the "key" field.
	// 键ID
	Key int `json:"key,omitempty"`
	// BoolV holds the value of the "bool_v" field.
	// BOOL值
	BoolV *bool `json:"bool_v,omitempty"`
	// StrV holds the value of the "str_v" field.
	// STRING值
	StrV *string `json:"str_v,omitempty"`
	// LongV holds the value of the "long_v" field.
	// LONG值
	LongV *int64 `json:"long_v,omitempty"`
	// DblV holds the value of the "dbl_v" field.
	// DOUBLE值
	DblV *float64 `json:"dbl_v,omitempty"`
	// JSONV holds the value of the "json_v" field.
	// JSON值
	JSONV *string `json:"json_v,omitempty"`
	// Ts holds the value of the "ts" field.
	// 时间戳
	Ts int64 `json:"ts,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TsKv) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case tskv.FieldBoolV:
			values[i] = new(sql.NullBool)
		case tskv.FieldDblV:
			values[i] = new(sql.NullFloat64)
		case tskv.FieldID, tskv.FieldKey, tskv.FieldLongV, tskv.FieldTs:
			values[i] = new(sql.NullInt64)
		case tskv.FieldStrV, tskv.FieldJSONV:
			values[i] = new(sql.NullString)
		case tskv.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TsKv", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TsKv fields.
func (tk *TsKv) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tskv.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tk.ID = int(value.Int64)
		case tskv.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				tk.EntityID = *value
			}
		case tskv.FieldKey:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				tk.Key = int(value.Int64)
			}
		case tskv.FieldBoolV:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field bool_v", values[i])
			} else if value.Valid {
				tk.BoolV = new(bool)
				*tk.BoolV = value.Bool
			}
		case tskv.FieldStrV:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field str_v", values[i])
			} else if value.Valid {
				tk.StrV = new(string)
				*tk.StrV = value.String
			}
		case tskv.FieldLongV:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field long_v", values[i])
			} else if value.Valid {
				tk.LongV = new(int64)
				*tk.LongV = value.Int64
			}
		case tskv.FieldDblV:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field dbl_v", values[i])
			} else if value.Valid {
				tk.DblV = new(float64)
				*tk.DblV = value.Float64
			}
		case tskv.FieldJSONV:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field json_v", values[i])
			} else if value.Valid {
				tk.JSONV = new(string)
				*tk.JSONV = value.String
			}
		case tskv.FieldTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				tk.Ts = value.Int64
			}
		}
	}
	return nil
}

// Update returns a builder for updating this TsKv.
// Note that you need to call TsKv.Unwrap() before calling this method if this TsKv
// was returned from a transaction, and the transaction was committed or rolled back.
func (tk *TsKv) Update() *TsKvUpdateOne {
	return (&TsKvClient{config: tk.config}).UpdateOne(tk)
}

// Unwrap unwraps the TsKv entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tk *TsKv) Unwrap() *TsKv {
	tx, ok := tk.config.driver.(*txDriver)
	if !ok {
		panic("ent: TsKv is not a transactional entity")
	}
	tk.config.driver = tx.drv
	return tk
}

// String implements the fmt.Stringer.
func (tk *TsKv) String() string {
	var builder strings.Builder
	builder.WriteString("TsKv(")
	builder.WriteString(fmt.Sprintf("id=%v", tk.ID))
	builder.WriteString(", entity_id=")
	builder.WriteString(fmt.Sprintf("%v", tk.EntityID))
	builder.WriteString(", key=")
	builder.WriteString(fmt.Sprintf("%v", tk.Key))
	if v := tk.BoolV; v != nil {
		builder.WriteString(", bool_v=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := tk.StrV; v != nil {
		builder.WriteString(", str_v=")
		builder.WriteString(*v)
	}
	if v := tk.LongV; v != nil {
		builder.WriteString(", long_v=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := tk.DblV; v != nil {
		builder.WriteString(", dbl_v=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	if v := tk.JSONV; v != nil {
		builder.WriteString(", json_v=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ts=")
	builder.WriteString(fmt.Sprintf("%v", tk.Ts))
	builder.WriteByte(')')
	return builder.String()
}

// TsKvs is a parsable slice of TsKv.
type TsKvs []*TsKv

func (tk TsKvs) config(cfg config) {
	for _i := range tk {
		tk[_i].config = cfg
	}
}
