// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskv"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TsKvQuery is the builder for querying TsKv entities.
type TsKvQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TsKv
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TsKvQuery builder.
func (tkq *TsKvQuery) Where(ps ...predicate.TsKv) *TsKvQuery {
	tkq.predicates = append(tkq.predicates, ps...)
	return tkq
}

// Limit adds a limit step to the query.
func (tkq *TsKvQuery) Limit(limit int) *TsKvQuery {
	tkq.limit = &limit
	return tkq
}

// Offset adds an offset step to the query.
func (tkq *TsKvQuery) Offset(offset int) *TsKvQuery {
	tkq.offset = &offset
	return tkq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tkq *TsKvQuery) Unique(unique bool) *TsKvQuery {
	tkq.unique = &unique
	return tkq
}

// Order adds an order step to the query.
func (tkq *TsKvQuery) Order(o ...OrderFunc) *TsKvQuery {
	tkq.order = append(tkq.order, o...)
	return tkq
}

// First returns the first TsKv entity from the query.
// Returns a *NotFoundError when no TsKv was found.
func (tkq *TsKvQuery) First(ctx context.Context) (*TsKv, error) {
	nodes, err := tkq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tskv.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tkq *TsKvQuery) FirstX(ctx context.Context) *TsKv {
	node, err := tkq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TsKv ID from the query.
// Returns a *NotFoundError when no TsKv ID was found.
func (tkq *TsKvQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tkq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tskv.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tkq *TsKvQuery) FirstIDX(ctx context.Context) int {
	id, err := tkq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TsKv entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TsKv entity is not found.
// Returns a *NotFoundError when no TsKv entities are found.
func (tkq *TsKvQuery) Only(ctx context.Context) (*TsKv, error) {
	nodes, err := tkq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tskv.Label}
	default:
		return nil, &NotSingularError{tskv.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tkq *TsKvQuery) OnlyX(ctx context.Context) *TsKv {
	node, err := tkq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TsKv ID in the query.
// Returns a *NotSingularError when exactly one TsKv ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tkq *TsKvQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tkq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = &NotSingularError{tskv.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tkq *TsKvQuery) OnlyIDX(ctx context.Context) int {
	id, err := tkq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TsKvs.
func (tkq *TsKvQuery) All(ctx context.Context) ([]*TsKv, error) {
	if err := tkq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tkq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tkq *TsKvQuery) AllX(ctx context.Context) []*TsKv {
	nodes, err := tkq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TsKv IDs.
func (tkq *TsKvQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tkq.Select(tskv.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tkq *TsKvQuery) IDsX(ctx context.Context) []int {
	ids, err := tkq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tkq *TsKvQuery) Count(ctx context.Context) (int, error) {
	if err := tkq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tkq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tkq *TsKvQuery) CountX(ctx context.Context) int {
	count, err := tkq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tkq *TsKvQuery) Exist(ctx context.Context) (bool, error) {
	if err := tkq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tkq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tkq *TsKvQuery) ExistX(ctx context.Context) bool {
	exist, err := tkq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TsKvQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tkq *TsKvQuery) Clone() *TsKvQuery {
	if tkq == nil {
		return nil
	}
	return &TsKvQuery{
		config:     tkq.config,
		limit:      tkq.limit,
		offset:     tkq.offset,
		order:      append([]OrderFunc{}, tkq.order...),
		predicates: append([]predicate.TsKv{}, tkq.predicates...),
		// clone intermediate query.
		sql:  tkq.sql.Clone(),
		path: tkq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EntityID uuid.UUID `json:"entity_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TsKv.Query().
//		GroupBy(tskv.FieldEntityID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tkq *TsKvQuery) GroupBy(field string, fields ...string) *TsKvGroupBy {
	group := &TsKvGroupBy{config: tkq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tkq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tkq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EntityID uuid.UUID `json:"entity_id,omitempty"`
//	}
//
//	client.TsKv.Query().
//		Select(tskv.FieldEntityID).
//		Scan(ctx, &v)
//
func (tkq *TsKvQuery) Select(fields ...string) *TsKvSelect {
	tkq.fields = append(tkq.fields, fields...)
	return &TsKvSelect{TsKvQuery: tkq}
}

func (tkq *TsKvQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tkq.fields {
		if !tskv.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tkq.path != nil {
		prev, err := tkq.path(ctx)
		if err != nil {
			return err
		}
		tkq.sql = prev
	}
	return nil
}

func (tkq *TsKvQuery) sqlAll(ctx context.Context) ([]*TsKv, error) {
	var (
		nodes = []*TsKv{}
		_spec = tkq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TsKv{config: tkq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(tkq.modifiers) > 0 {
		_spec.Modifiers = tkq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, tkq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tkq *TsKvQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tkq.querySpec()
	if len(tkq.modifiers) > 0 {
		_spec.Modifiers = tkq.modifiers
	}
	_spec.Node.Columns = tkq.fields
	if len(tkq.fields) > 0 {
		_spec.Unique = tkq.unique != nil && *tkq.unique
	}
	return sqlgraph.CountNodes(ctx, tkq.driver, _spec)
}

func (tkq *TsKvQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tkq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tkq *TsKvQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tskv.Table,
			Columns: tskv.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskv.FieldID,
			},
		},
		From:   tkq.sql,
		Unique: true,
	}
	if unique := tkq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tkq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tskv.FieldID)
		for i := range fields {
			if fields[i] != tskv.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tkq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tkq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tkq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tkq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tkq *TsKvQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tkq.driver.Dialect())
	t1 := builder.Table(tskv.Table)
	columns := tkq.fields
	if len(columns) == 0 {
		columns = tskv.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tkq.sql != nil {
		selector = tkq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tkq.unique != nil && *tkq.unique {
		selector.Distinct()
	}
	for _, m := range tkq.modifiers {
		m(selector)
	}
	for _, p := range tkq.predicates {
		p(selector)
	}
	for _, p := range tkq.order {
		p(selector)
	}
	if offset := tkq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tkq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tkq *TsKvQuery) Modify(modifiers ...func(s *sql.Selector)) *TsKvSelect {
	tkq.modifiers = append(tkq.modifiers, modifiers...)
	return tkq.Select()
}

// TsKvGroupBy is the group-by builder for TsKv entities.
type TsKvGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tkgb *TsKvGroupBy) Aggregate(fns ...AggregateFunc) *TsKvGroupBy {
	tkgb.fns = append(tkgb.fns, fns...)
	return tkgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tkgb *TsKvGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tkgb.path(ctx)
	if err != nil {
		return err
	}
	tkgb.sql = query
	return tkgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tkgb *TsKvGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tkgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tkgb.fields) > 1 {
		return nil, errors.New("ent: TsKvGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tkgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tkgb *TsKvGroupBy) StringsX(ctx context.Context) []string {
	v, err := tkgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tkgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tkgb *TsKvGroupBy) StringX(ctx context.Context) string {
	v, err := tkgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tkgb.fields) > 1 {
		return nil, errors.New("ent: TsKvGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tkgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tkgb *TsKvGroupBy) IntsX(ctx context.Context) []int {
	v, err := tkgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tkgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tkgb *TsKvGroupBy) IntX(ctx context.Context) int {
	v, err := tkgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tkgb.fields) > 1 {
		return nil, errors.New("ent: TsKvGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tkgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tkgb *TsKvGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tkgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tkgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tkgb *TsKvGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tkgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tkgb.fields) > 1 {
		return nil, errors.New("ent: TsKvGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tkgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tkgb *TsKvGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tkgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tkgb *TsKvGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tkgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tkgb *TsKvGroupBy) BoolX(ctx context.Context) bool {
	v, err := tkgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tkgb *TsKvGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tkgb.fields {
		if !tskv.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tkgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tkgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tkgb *TsKvGroupBy) sqlQuery() *sql.Selector {
	selector := tkgb.sql.Select()
	aggregation := make([]string, 0, len(tkgb.fns))
	for _, fn := range tkgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tkgb.fields)+len(tkgb.fns))
		for _, f := range tkgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tkgb.fields...)...)
}

// TsKvSelect is the builder for selecting fields of TsKv entities.
type TsKvSelect struct {
	*TsKvQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tks *TsKvSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tks.prepareQuery(ctx); err != nil {
		return err
	}
	tks.sql = tks.TsKvQuery.sqlQuery(ctx)
	return tks.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tks *TsKvSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tks.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tks.fields) > 1 {
		return nil, errors.New("ent: TsKvSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tks *TsKvSelect) StringsX(ctx context.Context) []string {
	v, err := tks.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tks.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tks *TsKvSelect) StringX(ctx context.Context) string {
	v, err := tks.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tks.fields) > 1 {
		return nil, errors.New("ent: TsKvSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tks *TsKvSelect) IntsX(ctx context.Context) []int {
	v, err := tks.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tks.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tks *TsKvSelect) IntX(ctx context.Context) int {
	v, err := tks.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tks.fields) > 1 {
		return nil, errors.New("ent: TsKvSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tks *TsKvSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tks.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tks.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tks *TsKvSelect) Float64X(ctx context.Context) float64 {
	v, err := tks.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tks.fields) > 1 {
		return nil, errors.New("ent: TsKvSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tks.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tks *TsKvSelect) BoolsX(ctx context.Context) []bool {
	v, err := tks.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tks *TsKvSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tks.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskv.Label}
	default:
		err = fmt.Errorf("ent: TsKvSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tks *TsKvSelect) BoolX(ctx context.Context) bool {
	v, err := tks.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tks *TsKvSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tks.sql.Query()
	if err := tks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tks *TsKvSelect) Modify(modifiers ...func(s *sql.Selector)) *TsKvSelect {
	tks.modifiers = append(tks.modifiers, modifiers...)
	return tks
}
