// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskv"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TsKvDelete is the builder for deleting a TsKv entity.
type TsKvDelete struct {
	config
	hooks    []Hook
	mutation *TsKvMutation
}

// Where appends a list predicates to the TsKvDelete builder.
func (tkd *TsKvDelete) Where(ps ...predicate.TsKv) *TsKvDelete {
	tkd.mutation.Where(ps...)
	return tkd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tkd *TsKvDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tkd.hooks) == 0 {
		affected, err = tkd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TsKvMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tkd.mutation = mutation
			affected, err = tkd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tkd.hooks) - 1; i >= 0; i-- {
			if tkd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tkd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tkd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tkd *TsKvDelete) ExecX(ctx context.Context) int {
	n, err := tkd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tkd *TsKvDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tskv.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskv.FieldID,
			},
		},
	}
	if ps := tkd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tkd.driver, _spec)
}

// TsKvDeleteOne is the builder for deleting a single TsKv entity.
type TsKvDeleteOne struct {
	tkd *TsKvDelete
}

// Exec executes the deletion query.
func (tkdo *TsKvDeleteOne) Exec(ctx context.Context) error {
	n, err := tkdo.tkd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tskv.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tkdo *TsKvDeleteOne) ExecX(ctx context.Context) {
	tkdo.tkd.ExecX(ctx)
}
