// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskvlatest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TsKvLatestUpdate is the builder for updating TsKvLatest entities.
type TsKvLatestUpdate struct {
	config
	hooks    []Hook
	mutation *TsKvLatestMutation
}

// Where appends a list predicates to the TsKvLatestUpdate builder.
func (tklu *TsKvLatestUpdate) Where(ps ...predicate.TsKvLatest) *TsKvLatestUpdate {
	tklu.mutation.Where(ps...)
	return tklu
}

// SetEntityID sets the "entity_id" field.
func (tklu *TsKvLatestUpdate) SetEntityID(u uuid.UUID) *TsKvLatestUpdate {
	tklu.mutation.SetEntityID(u)
	return tklu
}

// SetKey sets the "key" field.
func (tklu *TsKvLatestUpdate) SetKey(i int) *TsKvLatestUpdate {
	tklu.mutation.ResetKey()
	tklu.mutation.SetKey(i)
	return tklu
}

// AddKey adds i to the "key" field.
func (tklu *TsKvLatestUpdate) AddKey(i int) *TsKvLatestUpdate {
	tklu.mutation.AddKey(i)
	return tklu
}

// SetBoolV sets the "bool_v" field.
func (tklu *TsKvLatestUpdate) SetBoolV(b bool) *TsKvLatestUpdate {
	tklu.mutation.SetBoolV(b)
	return tklu
}

// SetNillableBoolV sets the "bool_v" field if the given value is not nil.
func (tklu *TsKvLatestUpdate) SetNillableBoolV(b *bool) *TsKvLatestUpdate {
	if b != nil {
		tklu.SetBoolV(*b)
	}
	return tklu
}

// ClearBoolV clears the value of the "bool_v" field.
func (tklu *TsKvLatestUpdate) ClearBoolV() *TsKvLatestUpdate {
	tklu.mutation.ClearBoolV()
	return tklu
}

// SetStrV sets the "str_v" field.
func (tklu *TsKvLatestUpdate) SetStrV(s string) *TsKvLatestUpdate {
	tklu.mutation.SetStrV(s)
	return tklu
}

// SetNillableStrV sets the "str_v" field if the given value is not nil.
func (tklu *TsKvLatestUpdate) SetNillableStrV(s *string) *TsKvLatestUpdate {
	if s != nil {
		tklu.SetStrV(*s)
	}
	return tklu
}

// ClearStrV clears the value of the "str_v" field.
func (tklu *TsKvLatestUpdate) ClearStrV() *TsKvLatestUpdate {
	tklu.mutation.ClearStrV()
	return tklu
}

// SetLongV sets the "long_v" field.
func (tklu *TsKvLatestUpdate) SetLongV(i int64) *TsKvLatestUpdate {
	tklu.mutation.ResetLongV()
	tklu.mutation.SetLongV(i)
	return tklu
}

// SetNillableLongV sets the "long_v" field if the given value is not nil.
func (tklu *TsKvLatestUpdate) SetNillableLongV(i *int64) *TsKvLatestUpdate {
	if i != nil {
		tklu.SetLongV(*i)
	}
	return tklu
}

// AddLongV adds i to the "long_v" field.
func (tklu *TsKvLatestUpdate) AddLongV(i int64) *TsKvLatestUpdate {
	tklu.mutation.AddLongV(i)
	return tklu
}

// ClearLongV clears the value of the "long_v" field.
func (tklu *TsKvLatestUpdate) ClearLongV() *TsKvLatestUpdate {
	tklu.mutation.ClearLongV()
	return tklu
}

// SetDblV sets the "dbl_v" field.
func (tklu *TsKvLatestUpdate) SetDblV(f float64) *TsKvLatestUpdate {
	tklu.mutation.ResetDblV()
	tklu.mutation.SetDblV(f)
	return tklu
}

// SetNillableDblV sets the "dbl_v" field if the given value is not nil.
func (tklu *TsKvLatestUpdate) SetNillableDblV(f *float64) *TsKvLatestUpdate {
	if f != nil {
		tklu.SetDblV(*f)
	}
	return tklu
}

// AddDblV adds f to the "dbl_v" field.
func (tklu *TsKvLatestUpdate) AddDblV(f float64) *TsKvLatestUpdate {
	tklu.mutation.AddDblV(f)
	return tklu
}

// ClearDblV clears the value of the "dbl_v" field.
func (tklu *TsKvLatestUpdate) ClearDblV() *TsKvLatestUpdate {
	tklu.mutation.ClearDblV()
	return tklu
}

// SetJSONV sets the "json_v" field.
func (tklu *TsKvLatestUpdate) SetJSONV(s string) *TsKvLatestUpdate {
	tklu.mutation.SetJSONV(s)
	return tklu
}

// SetNillableJSONV sets the "json_v" field if the given value is not nil.
func (tklu *TsKvLatestUpdate) SetNillableJSONV(s *string) *TsKvLatestUpdate {
	if s != nil {
		tklu.SetJSONV(*s)
	}
	return tklu
}

// ClearJSONV clears the value of the "json_v" field.
func (tklu *TsKvLatestUpdate) ClearJSONV() *TsKvLatestUpdate {
	tklu.mutation.ClearJSONV()
	return tklu
}

// SetTs sets the "ts" field.
func (tklu *TsKvLatestUpdate) SetTs(i int64) *TsKvLatestUpdate {
	tklu.mutation.ResetTs()
	tklu.mutation.SetTs(i)
	return tklu
}

// AddTs adds i to the "ts" field.
func (tklu *TsKvLatestUpdate) AddTs(i int64) *TsKvLatestUpdate {
	tklu.mutation.AddTs(i)
	return tklu
}

// Mutation returns the TsKvLatestMutation object of the builder.
func (tklu *TsKvLatestUpdate) Mutation() *TsKvLatestMutation {
	return tklu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tklu *TsKvLatestUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tklu.hooks) == 0 {
		if err = tklu.check(); err != nil {
			return 0, err
		}
		affected, err = tklu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TsKvLatestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tklu.check(); err != nil {
				return 0, err
			}
			tklu.mutation = mutation
			affected, err = tklu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tklu.hooks) - 1; i >= 0; i-- {
			if tklu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tklu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tklu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tklu *TsKvLatestUpdate) SaveX(ctx context.Context) int {
	affected, err := tklu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tklu *TsKvLatestUpdate) Exec(ctx context.Context) error {
	_, err := tklu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tklu *TsKvLatestUpdate) ExecX(ctx context.Context) {
	if err := tklu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tklu *TsKvLatestUpdate) check() error {
	if v, ok := tklu.mutation.StrV(); ok {
		if err := tskvlatest.StrVValidator(v); err != nil {
			return &ValidationError{Name: "str_v", err: fmt.Errorf(`ent: validator failed for field "TsKvLatest.str_v": %w`, err)}
		}
	}
	return nil
}

func (tklu *TsKvLatestUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tskvlatest.Table,
			Columns: tskvlatest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvlatest.FieldID,
			},
		},
	}
	if ps := tklu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tklu.mutation.EntityID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: tskvlatest.FieldEntityID,
		})
	}
	if value, ok := tklu.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tskvlatest.FieldKey,
		})
	}
	if value, ok := tklu.mutation.AddedKey(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tskvlatest.FieldKey,
		})
	}
	if value, ok := tklu.mutation.BoolV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tskvlatest.FieldBoolV,
		})
	}
	if tklu.mutation.BoolVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: tskvlatest.FieldBoolV,
		})
	}
	if value, ok := tklu.mutation.StrV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldStrV,
		})
	}
	if tklu.mutation.StrVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: tskvlatest.FieldStrV,
		})
	}
	if value, ok := tklu.mutation.LongV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldLongV,
		})
	}
	if value, ok := tklu.mutation.AddedLongV(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldLongV,
		})
	}
	if tklu.mutation.LongVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: tskvlatest.FieldLongV,
		})
	}
	if value, ok := tklu.mutation.DblV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: tskvlatest.FieldDblV,
		})
	}
	if value, ok := tklu.mutation.AddedDblV(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: tskvlatest.FieldDblV,
		})
	}
	if tklu.mutation.DblVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: tskvlatest.FieldDblV,
		})
	}
	if value, ok := tklu.mutation.JSONV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldJSONV,
		})
	}
	if tklu.mutation.JSONVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: tskvlatest.FieldJSONV,
		})
	}
	if value, ok := tklu.mutation.Ts(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldTs,
		})
	}
	if value, ok := tklu.mutation.AddedTs(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldTs,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tklu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tskvlatest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TsKvLatestUpdateOne is the builder for updating a single TsKvLatest entity.
type TsKvLatestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TsKvLatestMutation
}

// SetEntityID sets the "entity_id" field.
func (tkluo *TsKvLatestUpdateOne) SetEntityID(u uuid.UUID) *TsKvLatestUpdateOne {
	tkluo.mutation.SetEntityID(u)
	return tkluo
}

// SetKey sets the "key" field.
func (tkluo *TsKvLatestUpdateOne) SetKey(i int) *TsKvLatestUpdateOne {
	tkluo.mutation.ResetKey()
	tkluo.mutation.SetKey(i)
	return tkluo
}

// AddKey adds i to the "key" field.
func (tkluo *TsKvLatestUpdateOne) AddKey(i int) *TsKvLatestUpdateOne {
	tkluo.mutation.AddKey(i)
	return tkluo
}

// SetBoolV sets the "bool_v" field.
func (tkluo *TsKvLatestUpdateOne) SetBoolV(b bool) *TsKvLatestUpdateOne {
	tkluo.mutation.SetBoolV(b)
	return tkluo
}

// SetNillableBoolV sets the "bool_v" field if the given value is not nil.
func (tkluo *TsKvLatestUpdateOne) SetNillableBoolV(b *bool) *TsKvLatestUpdateOne {
	if b != nil {
		tkluo.SetBoolV(*b)
	}
	return tkluo
}

// ClearBoolV clears the value of the "bool_v" field.
func (tkluo *TsKvLatestUpdateOne) ClearBoolV() *TsKvLatestUpdateOne {
	tkluo.mutation.ClearBoolV()
	return tkluo
}

// SetStrV sets the "str_v" field.
func (tkluo *TsKvLatestUpdateOne) SetStrV(s string) *TsKvLatestUpdateOne {
	tkluo.mutation.SetStrV(s)
	return tkluo
}

// SetNillableStrV sets the "str_v" field if the given value is not nil.
func (tkluo *TsKvLatestUpdateOne) SetNillableStrV(s *string) *TsKvLatestUpdateOne {
	if s != nil {
		tkluo.SetStrV(*s)
	}
	return tkluo
}

// ClearStrV clears the value of the "str_v" field.
func (tkluo *TsKvLatestUpdateOne) ClearStrV() *TsKvLatestUpdateOne {
	tkluo.mutation.ClearStrV()
	return tkluo
}

// SetLongV sets the "long_v" field.
func (tkluo *TsKvLatestUpdateOne) SetLongV(i int64) *TsKvLatestUpdateOne {
	tkluo.mutation.ResetLongV()
	tkluo.mutation.SetLongV(i)
	return tkluo
}

// SetNillableLongV sets the "long_v" field if the given value is not nil.
func (tkluo *TsKvLatestUpdateOne) SetNillableLongV(i *int64) *TsKvLatestUpdateOne {
	if i != nil {
		tkluo.SetLongV(*i)
	}
	return tkluo
}

// AddLongV adds i to the "long_v" field.
func (tkluo *TsKvLatestUpdateOne) AddLongV(i int64) *TsKvLatestUpdateOne {
	tkluo.mutation.AddLongV(i)
	return tkluo
}

// ClearLongV clears the value of the "long_v" field.
func (tkluo *TsKvLatestUpdateOne) ClearLongV() *TsKvLatestUpdateOne {
	tkluo.mutation.ClearLongV()
	return tkluo
}

// SetDblV sets the "dbl_v" field.
func (tkluo *TsKvLatestUpdateOne) SetDblV(f float64) *TsKvLatestUpdateOne {
	tkluo.mutation.ResetDblV()
	tkluo.mutation.SetDblV(f)
	return tkluo
}

// SetNillableDblV sets the "dbl_v" field if the given value is not nil.
func (tkluo *TsKvLatestUpdateOne) SetNillableDblV(f *float64) *TsKvLatestUpdateOne {
	if f != nil {
		tkluo.SetDblV(*f)
	}
	return tkluo
}

// AddDblV adds f to the "dbl_v" field.
func (tkluo *TsKvLatestUpdateOne) AddDblV(f float64) *TsKvLatestUpdateOne {
	tkluo.mutation.AddDblV(f)
	return tkluo
}

// ClearDblV clears the value of the "dbl_v" field.
func (tkluo *TsKvLatestUpdateOne) ClearDblV() *TsKvLatestUpdateOne {
	tkluo.mutation.ClearDblV()
	return tkluo
}

// SetJSONV sets the "json_v" field.
func (tkluo *TsKvLatestUpdateOne) SetJSONV(s string) *TsKvLatestUpdateOne {
	tkluo.mutation.SetJSONV(s)
	return tkluo
}

// SetNillableJSONV sets the "json_v" field if the given value is not nil.
func (tkluo *TsKvLatestUpdateOne) SetNillableJSONV(s *string) *TsKvLatestUpdateOne {
	if s != nil {
		tkluo.SetJSONV(*s)
	}
	return tkluo
}

// ClearJSONV clears the value of the "json_v" field.
func (tkluo *TsKvLatestUpdateOne) ClearJSONV() *TsKvLatestUpdateOne {
	tkluo.mutation.ClearJSONV()
	return tkluo
}

// SetTs sets the "ts" field.
func (tkluo *TsKvLatestUpdateOne) SetTs(i int64) *TsKvLatestUpdateOne {
	tkluo.mutation.ResetTs()
	tkluo.mutation.SetTs(i)
	return tkluo
}

// AddTs adds i to the "ts" field.
func (tkluo *TsKvLatestUpdateOne) AddTs(i int64) *TsKvLatestUpdateOne {
	tkluo.mutation.AddTs(i)
	return tkluo
}

// Mutation returns the TsKvLatestMutation object of the builder.
func (tkluo *TsKvLatestUpdateOne) Mutation() *TsKvLatestMutation {
	return tkluo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tkluo *TsKvLatestUpdateOne) Select(field string, fields ...string) *TsKvLatestUpdateOne {
	tkluo.fields = append([]string{field}, fields...)
	return tkluo
}

// Save executes the query and returns the updated TsKvLatest entity.
func (tkluo *TsKvLatestUpdateOne) Save(ctx context.Context) (*TsKvLatest, error) {
	var (
		err  error
		node *TsKvLatest
	)
	if len(tkluo.hooks) == 0 {
		if err = tkluo.check(); err != nil {
			return nil, err
		}
		node, err = tkluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TsKvLatestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tkluo.check(); err != nil {
				return nil, err
			}
			tkluo.mutation = mutation
			node, err = tkluo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tkluo.hooks) - 1; i >= 0; i-- {
			if tkluo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tkluo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tkluo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tkluo *TsKvLatestUpdateOne) SaveX(ctx context.Context) *TsKvLatest {
	node, err := tkluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tkluo *TsKvLatestUpdateOne) Exec(ctx context.Context) error {
	_, err := tkluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tkluo *TsKvLatestUpdateOne) ExecX(ctx context.Context) {
	if err := tkluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tkluo *TsKvLatestUpdateOne) check() error {
	if v, ok := tkluo.mutation.StrV(); ok {
		if err := tskvlatest.StrVValidator(v); err != nil {
			return &ValidationError{Name: "str_v", err: fmt.Errorf(`ent: validator failed for field "TsKvLatest.str_v": %w`, err)}
		}
	}
	return nil
}

func (tkluo *TsKvLatestUpdateOne) sqlSave(ctx context.Context) (_node *TsKvLatest, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tskvlatest.Table,
			Columns: tskvlatest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvlatest.FieldID,
			},
		},
	}
	id, ok := tkluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TsKvLatest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tkluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tskvlatest.FieldID)
		for _, f := range fields {
			if !tskvlatest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tskvlatest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tkluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tkluo.mutation.EntityID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: tskvlatest.FieldEntityID,
		})
	}
	if value, ok := tkluo.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tskvlatest.FieldKey,
		})
	}
	if value, ok := tkluo.mutation.AddedKey(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tskvlatest.FieldKey,
		})
	}
	if value, ok := tkluo.mutation.BoolV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tskvlatest.FieldBoolV,
		})
	}
	if tkluo.mutation.BoolVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: tskvlatest.FieldBoolV,
		})
	}
	if value, ok := tkluo.mutation.StrV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldStrV,
		})
	}
	if tkluo.mutation.StrVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: tskvlatest.FieldStrV,
		})
	}
	if value, ok := tkluo.mutation.LongV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldLongV,
		})
	}
	if value, ok := tkluo.mutation.AddedLongV(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldLongV,
		})
	}
	if tkluo.mutation.LongVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Column: tskvlatest.FieldLongV,
		})
	}
	if value, ok := tkluo.mutation.DblV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: tskvlatest.FieldDblV,
		})
	}
	if value, ok := tkluo.mutation.AddedDblV(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: tskvlatest.FieldDblV,
		})
	}
	if tkluo.mutation.DblVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: tskvlatest.FieldDblV,
		})
	}
	if value, ok := tkluo.mutation.JSONV(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tskvlatest.FieldJSONV,
		})
	}
	if tkluo.mutation.JSONVCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: tskvlatest.FieldJSONV,
		})
	}
	if value, ok := tkluo.mutation.Ts(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldTs,
		})
	}
	if value, ok := tkluo.mutation.AddedTs(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: tskvlatest.FieldTs,
		})
	}
	_node = &TsKvLatest{config: tkluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tkluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tskvlatest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
