// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsdb-ent-example/ent/predicate"
	"tsdb-ent-example/ent/tskvlatest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TsKvLatestQuery is the builder for querying TsKvLatest entities.
type TsKvLatestQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TsKvLatest
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TsKvLatestQuery builder.
func (tklq *TsKvLatestQuery) Where(ps ...predicate.TsKvLatest) *TsKvLatestQuery {
	tklq.predicates = append(tklq.predicates, ps...)
	return tklq
}

// Limit adds a limit step to the query.
func (tklq *TsKvLatestQuery) Limit(limit int) *TsKvLatestQuery {
	tklq.limit = &limit
	return tklq
}

// Offset adds an offset step to the query.
func (tklq *TsKvLatestQuery) Offset(offset int) *TsKvLatestQuery {
	tklq.offset = &offset
	return tklq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tklq *TsKvLatestQuery) Unique(unique bool) *TsKvLatestQuery {
	tklq.unique = &unique
	return tklq
}

// Order adds an order step to the query.
func (tklq *TsKvLatestQuery) Order(o ...OrderFunc) *TsKvLatestQuery {
	tklq.order = append(tklq.order, o...)
	return tklq
}

// First returns the first TsKvLatest entity from the query.
// Returns a *NotFoundError when no TsKvLatest was found.
func (tklq *TsKvLatestQuery) First(ctx context.Context) (*TsKvLatest, error) {
	nodes, err := tklq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tskvlatest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tklq *TsKvLatestQuery) FirstX(ctx context.Context) *TsKvLatest {
	node, err := tklq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TsKvLatest ID from the query.
// Returns a *NotFoundError when no TsKvLatest ID was found.
func (tklq *TsKvLatestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tklq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tskvlatest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tklq *TsKvLatestQuery) FirstIDX(ctx context.Context) int {
	id, err := tklq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TsKvLatest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TsKvLatest entity is not found.
// Returns a *NotFoundError when no TsKvLatest entities are found.
func (tklq *TsKvLatestQuery) Only(ctx context.Context) (*TsKvLatest, error) {
	nodes, err := tklq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tskvlatest.Label}
	default:
		return nil, &NotSingularError{tskvlatest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tklq *TsKvLatestQuery) OnlyX(ctx context.Context) *TsKvLatest {
	node, err := tklq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TsKvLatest ID in the query.
// Returns a *NotSingularError when exactly one TsKvLatest ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tklq *TsKvLatestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tklq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = &NotSingularError{tskvlatest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tklq *TsKvLatestQuery) OnlyIDX(ctx context.Context) int {
	id, err := tklq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TsKvLatests.
func (tklq *TsKvLatestQuery) All(ctx context.Context) ([]*TsKvLatest, error) {
	if err := tklq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tklq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tklq *TsKvLatestQuery) AllX(ctx context.Context) []*TsKvLatest {
	nodes, err := tklq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TsKvLatest IDs.
func (tklq *TsKvLatestQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tklq.Select(tskvlatest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tklq *TsKvLatestQuery) IDsX(ctx context.Context) []int {
	ids, err := tklq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tklq *TsKvLatestQuery) Count(ctx context.Context) (int, error) {
	if err := tklq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tklq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tklq *TsKvLatestQuery) CountX(ctx context.Context) int {
	count, err := tklq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tklq *TsKvLatestQuery) Exist(ctx context.Context) (bool, error) {
	if err := tklq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tklq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tklq *TsKvLatestQuery) ExistX(ctx context.Context) bool {
	exist, err := tklq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TsKvLatestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tklq *TsKvLatestQuery) Clone() *TsKvLatestQuery {
	if tklq == nil {
		return nil
	}
	return &TsKvLatestQuery{
		config:     tklq.config,
		limit:      tklq.limit,
		offset:     tklq.offset,
		order:      append([]OrderFunc{}, tklq.order...),
		predicates: append([]predicate.TsKvLatest{}, tklq.predicates...),
		// clone intermediate query.
		sql:  tklq.sql.Clone(),
		path: tklq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EntityID uuid.UUID `json:"entity_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TsKvLatest.Query().
//		GroupBy(tskvlatest.FieldEntityID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tklq *TsKvLatestQuery) GroupBy(field string, fields ...string) *TsKvLatestGroupBy {
	group := &TsKvLatestGroupBy{config: tklq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tklq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tklq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EntityID uuid.UUID `json:"entity_id,omitempty"`
//	}
//
//	client.TsKvLatest.Query().
//		Select(tskvlatest.FieldEntityID).
//		Scan(ctx, &v)
//
func (tklq *TsKvLatestQuery) Select(fields ...string) *TsKvLatestSelect {
	tklq.fields = append(tklq.fields, fields...)
	return &TsKvLatestSelect{TsKvLatestQuery: tklq}
}

func (tklq *TsKvLatestQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tklq.fields {
		if !tskvlatest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tklq.path != nil {
		prev, err := tklq.path(ctx)
		if err != nil {
			return err
		}
		tklq.sql = prev
	}
	return nil
}

func (tklq *TsKvLatestQuery) sqlAll(ctx context.Context) ([]*TsKvLatest, error) {
	var (
		nodes = []*TsKvLatest{}
		_spec = tklq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TsKvLatest{config: tklq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(tklq.modifiers) > 0 {
		_spec.Modifiers = tklq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, tklq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tklq *TsKvLatestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tklq.querySpec()
	if len(tklq.modifiers) > 0 {
		_spec.Modifiers = tklq.modifiers
	}
	_spec.Node.Columns = tklq.fields
	if len(tklq.fields) > 0 {
		_spec.Unique = tklq.unique != nil && *tklq.unique
	}
	return sqlgraph.CountNodes(ctx, tklq.driver, _spec)
}

func (tklq *TsKvLatestQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tklq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tklq *TsKvLatestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tskvlatest.Table,
			Columns: tskvlatest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tskvlatest.FieldID,
			},
		},
		From:   tklq.sql,
		Unique: true,
	}
	if unique := tklq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tklq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tskvlatest.FieldID)
		for i := range fields {
			if fields[i] != tskvlatest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tklq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tklq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tklq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tklq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tklq *TsKvLatestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tklq.driver.Dialect())
	t1 := builder.Table(tskvlatest.Table)
	columns := tklq.fields
	if len(columns) == 0 {
		columns = tskvlatest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tklq.sql != nil {
		selector = tklq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tklq.unique != nil && *tklq.unique {
		selector.Distinct()
	}
	for _, m := range tklq.modifiers {
		m(selector)
	}
	for _, p := range tklq.predicates {
		p(selector)
	}
	for _, p := range tklq.order {
		p(selector)
	}
	if offset := tklq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tklq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tklq *TsKvLatestQuery) Modify(modifiers ...func(s *sql.Selector)) *TsKvLatestSelect {
	tklq.modifiers = append(tklq.modifiers, modifiers...)
	return tklq.Select()
}

// TsKvLatestGroupBy is the group-by builder for TsKvLatest entities.
type TsKvLatestGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tklgb *TsKvLatestGroupBy) Aggregate(fns ...AggregateFunc) *TsKvLatestGroupBy {
	tklgb.fns = append(tklgb.fns, fns...)
	return tklgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tklgb *TsKvLatestGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tklgb.path(ctx)
	if err != nil {
		return err
	}
	tklgb.sql = query
	return tklgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tklgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tklgb.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tklgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) StringsX(ctx context.Context) []string {
	v, err := tklgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tklgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) StringX(ctx context.Context) string {
	v, err := tklgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tklgb.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tklgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) IntsX(ctx context.Context) []int {
	v, err := tklgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tklgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) IntX(ctx context.Context) int {
	v, err := tklgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tklgb.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tklgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tklgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tklgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tklgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tklgb.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tklgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tklgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tklgb *TsKvLatestGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tklgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tklgb *TsKvLatestGroupBy) BoolX(ctx context.Context) bool {
	v, err := tklgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tklgb *TsKvLatestGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tklgb.fields {
		if !tskvlatest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tklgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tklgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tklgb *TsKvLatestGroupBy) sqlQuery() *sql.Selector {
	selector := tklgb.sql.Select()
	aggregation := make([]string, 0, len(tklgb.fns))
	for _, fn := range tklgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tklgb.fields)+len(tklgb.fns))
		for _, f := range tklgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tklgb.fields...)...)
}

// TsKvLatestSelect is the builder for selecting fields of TsKvLatest entities.
type TsKvLatestSelect struct {
	*TsKvLatestQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tkls *TsKvLatestSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tkls.prepareQuery(ctx); err != nil {
		return err
	}
	tkls.sql = tkls.TsKvLatestQuery.sqlQuery(ctx)
	return tkls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tkls *TsKvLatestSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tkls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tkls.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tkls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tkls *TsKvLatestSelect) StringsX(ctx context.Context) []string {
	v, err := tkls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tkls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tkls *TsKvLatestSelect) StringX(ctx context.Context) string {
	v, err := tkls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tkls.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tkls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tkls *TsKvLatestSelect) IntsX(ctx context.Context) []int {
	v, err := tkls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tkls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tkls *TsKvLatestSelect) IntX(ctx context.Context) int {
	v, err := tkls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tkls.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tkls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tkls *TsKvLatestSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tkls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tkls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tkls *TsKvLatestSelect) Float64X(ctx context.Context) float64 {
	v, err := tkls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tkls.fields) > 1 {
		return nil, errors.New("ent: TsKvLatestSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tkls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tkls *TsKvLatestSelect) BoolsX(ctx context.Context) []bool {
	v, err := tkls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tkls *TsKvLatestSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tkls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tskvlatest.Label}
	default:
		err = fmt.Errorf("ent: TsKvLatestSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tkls *TsKvLatestSelect) BoolX(ctx context.Context) bool {
	v, err := tkls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tkls *TsKvLatestSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tkls.sql.Query()
	if err := tkls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tkls *TsKvLatestSelect) Modify(modifiers ...func(s *sql.Selector)) *TsKvLatestSelect {
	tkls.modifiers = append(tkls.modifiers, modifiers...)
	return tkls
}
