// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AttributeKV is the predicate function for attributekv builders.
type AttributeKV func(*sql.Selector)

// Sensor is the predicate function for sensor builders.
type Sensor func(*sql.Selector)

// SensorData is the predicate function for sensordata builders.
type SensorData func(*sql.Selector)

// TsKv is the predicate function for tskv builders.
type TsKv func(*sql.Selector)

// TsKvDictionary is the predicate function for tskvdictionary builders.
type TsKvDictionary func(*sql.Selector)

// TsKvLatest is the predicate function for tskvlatest builders.
type TsKvLatest func(*sql.Selector)
